Add Labels API section to nav bar
forta-network/docs pull request #210
Opened 2023-04-03 21:33 UTC by emnul

2023-04-05 14:23 UTC, Robert-H-Leonard requested changes

2023-04-05 14:23 UTC, Robert-H-Leonard commented on mkdocs.yml
> +      - Adding Labels to Findings: labels.md
Could you also move the existing docs over to this new section?

2023-04-05 14:24 UTC, Robert-H-Leonard approved these changes

2023-04-06 16:16 UTC, stevenlanders commented
Let's avoid merging this - we're going to go behind graphql instead.

2023-04-06 16:16 UTC, closed without merging